name: CraftFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.4
description: Plugin made for CraftFreedom.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon, OxLemonxO]

# plugin.yml is no longer used to define commands.
